train:
  - './data/UCY/UCY_Dataset_time0-54_timeunit0.08.npy'
  - './data/UCY/UCY_Dataset_time54-108_timeunit0.08.npy'
  - './data/UCY/UCY_Dataset_time108-162_timeunit0.08.npy'

test:
  - './data/UCY/UCY_Dataset_time162-216_timeunit0.08.npy'